### ISSUE TITLE
Filter on flexible arguments

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/in-the-trees#13]
Maybe I'm not seeing something.

I would *like* to be able to pass duckdbfs a set of arguments and have it perform filter operations using those, without having to spell out in advance what all those arguments will be.

Like this:

```
my_filter_fxn <- filter(my_data, filter_criteria){
    filter(my_data, filter_criteria)
}
```

behaving something like 

```
my_filter_fxn(my_data, filter_criteria = c("coat == 'calico'"))
```

returning all rows of `my_data` with `coat==calico`. This is easy to do if you know to expect certain args, but I don't know how to do it if you don't know in advance whether the function is going to be called to filter based on coat, or on whisker length, or whatever.

**Comment by diazrenata** [comment]
(It is also not impossible to do using bracket subsetting, but I want to do this using duckdbfs which to my knowledge works with dplyr syntax).

**Comment by diazrenata** [comment]
https://dplyr.tidyverse.org/articles/programming.html#transforming-user-supplied-variables

looks like you could parse something.

**Comment by diazrenata** [comment]
https://stackoverflow.com/questions/24569154/use-variable-names-in-functions-of-dplyr :eyes:

**Comment by diazrenata** [comment]
```
filter_on_passed_vars <- function(df, conditions = list("NYEARS == 2",
                                                        "TREE_UNIQUE_ID == 27_3_65_20067_3_19")) {
  
  splitcond = lapply(conditions, strsplit, split = " ") 
  
  call1 <- call(splitcond[[2]][[1]][2], as.name(splitcond[[2]][[1]][1]),
                                         (splitcond[[2]][[1]][3]))
  calls <- lapply(splitcond, FUN = function(a_split_condition)  call(a_split_condition[[1]][2], as.name(a_split_condition[[1]][1]),
                                                                     (a_split_condition[[1]][3])))
  
  df |>
    mutate_all(as.character()) |>
    filter(!!!calls)
}
```

This works but there is a warning about the `!!!` eval syntax.

**Comment by diazrenata** [comment]
I have this working. https://github.com/diazrenata/in-the-trees/blob/main/R/query_tables.R

**Comment by diazrenata** [comment]
@Aariq Here is where I had notes on passing variable and function names to `filter`, etc.

**Comment by Aariq** [comment]
You can do this with `rlang` like so:

``` r
f4 <- function(...) {
  exprs <- rlang::enquos(...)
  iris |> 
    dplyr::filter(!!!exprs)
}

f4(Species == 'setosa', Petal.Width < 0.3, Sepal.Length == 5.1)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          5.1         3.4          1.5         0.2  setosa
#> 3          5.1         3.8          1.6         0.2  setosa
```

<sup>Created on 2024-01-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Not sure how to get this working with a list as an input, only with `...`

**Comment by diazrenata** [comment]
Cool, I'll see if this can work!
